language: java

jdk:
  - openjdk8
# 28-Sep-2017, tatu: Alas, to work on JDK9 would need to include deps for JAXB and
#    we do and can not rely on JDK9 for long time to come. So, leave out
  - openjdk9

branches:
  only:
    - master
    - "3.0"
