language: java

jdk:
  - openjdk8
  - openjdk11

# Below this line is configuration for deploying to the Sonatype OSS repo
# https://knowm.org/configure-travis-ci-to-deploy-snapshots/
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
after_success:
  - "mvn -B source:jar javadoc:jar deploy --settings target/travis/settings.xml"

branches:
  only:
    - master
    - "2.11"

env:
  global:
    - secure: ""
    - secure: ""
